/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANFESTIVAL_MASTER_H
#define CANFESTIVAL_MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern INTEGER32 D0;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 D1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 D2;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // CANFESTIVAL_MASTER_H 
