
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANFESTIVAL_MASTER_H
#define CANFESTIVAL_MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 _valueRangeTest (UNS8 typeValue, void * value);
const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data masterObjdict_Data;
extern INTEGER32 D0;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 D1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 D2;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

extern UNS16 Servo_Motor_Parameters_Motor_SN;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS8 Servo_Motor_Parameters_Compatibility_Entry[2];		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS32 Servo_Motor_Parameters_Customized_motor_SN;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS16 Servo_Motor_Parameters_Encoder_Version;		/* Mapped at index 0x2000, subindex 0x05 */
extern UNS16 Servo_Motor_Parameters_Bus_motor_SN;		/* Mapped at index 0x2000, subindex 0x06 */
extern UNS16 Servo_Drive_Parameters_DSP_Software_Version;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS16 Servo_Drive_Parameters_Fpga_Software_Version;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS16 Servo_Drive_Parameters_Servo_drive_SN;		/* Mapped at index 0x2001, subindex 0x03 */
extern UNS16 Basic_Control_Parameters_Control_mode;		/* Mapped at index 0x2002, subindex 0x01 */
extern UNS16 Basic_Control_Parameters_BP_AbsPosDetectionSel;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS16 Basic_Control_Parameters_Rotating_direction;		/* Mapped at index 0x2002, subindex 0x03 */
extern UNS16 Basic_Control_Parameters_Direction_of_output_pulse;		/* Mapped at index 0x2002, subindex 0x04 */
extern UNS8 Basic_Control_Parameters_Compatibility_Entry[14];		/* Mapped at index 0x2002, subindex 0x05 */
extern UNS16 Basic_Control_Parameters_Stop_mode_at_servo_drive_disabled;		/* Mapped at index 0x2002, subindex 0x06 */
extern UNS16 Basic_Control_Parameters_Stop_mode_at_fault_2;		/* Mapped at index 0x2002, subindex 0x07 */
extern UNS16 Basic_Control_Parameters_Stop_mode_at_overtravel;		/* Mapped at index 0x2002, subindex 0x08 */
extern UNS16 Basic_Control_Parameters_Stop_mode_at_fault_1;		/* Mapped at index 0x2002, subindex 0x09 */
extern UNS16 Basic_Control_Parameters_Brake_release_command_delay_at_servo_drive_enabled;		/* Mapped at index 0x2002, subindex 0x0A */
extern UNS16 Basic_Control_Parameters_Servo_drive_disable_delay_at_brake_apply_command;		/* Mapped at index 0x2002, subindex 0x0B */
extern UNS16 Basic_Control_Parameters_Output_speed_limit_of_brake_reference;		/* Mapped at index 0x2002, subindex 0x0C */
extern UNS16 Basic_Control_Parameters_Waiting_time_from_servo_disable_signal_to_brake_apply_command;		/* Mapped at index 0x2002, subindex 0x0D */
extern UNS16 Basic_Control_Parameters_Switch_speed_of_stop_mode_and_stop_speed;		/* Mapped at index 0x2002, subindex 0x0F */
extern UNS16 Basic_Control_Parameters_Display_of_keypad_warning;		/* Mapped at index 0x2002, subindex 0x10 */
extern UNS16 Basic_Control_Parameters_Filter_time_of_servo_ON_signal;		/* Mapped at index 0x2002, subindex 0x13 */
extern UNS16 Basic_Control_Parameters_Allowed_minimum_braking_resistance;		/* Mapped at index 0x2002, subindex 0x16 */
extern UNS16 Basic_Control_Parameters_Power_of_built_in_braking_resistor;		/* Mapped at index 0x2002, subindex 0x17 */
extern UNS16 Basic_Control_Parameters_Resistance_of_built_in_braking_resistor;		/* Mapped at index 0x2002, subindex 0x18 */
extern UNS16 Basic_Control_Parameters_Resistor_heat_dissipation_coefficient;		/* Mapped at index 0x2002, subindex 0x19 */
extern UNS16 Basic_Control_Parameters_braking_resistor_type;		/* Mapped at index 0x2002, subindex 0x1A */
extern UNS16 Basic_Control_Parameters_Power_of_external_dynamic_resistor;		/* Mapped at index 0x2002, subindex 0x1B */
extern UNS16 Basic_Control_Parameters_Resistance_of_external_braking_resistor;		/* Mapped at index 0x2002, subindex 0x1C */
extern UNS16 Basic_Control_Parameters_Parameter_initialization;		/* Mapped at index 0x2002, subindex 0x20 */
extern UNS16 Basic_Control_Parameters_Default_keypad_display;		/* Mapped at index 0x2002, subindex 0x21 */
extern UNS16 Basic_Control_Parameters_CAN_software_version;		/* Mapped at index 0x2002, subindex 0x23 */
extern UNS16 Basic_Control_Parameters_Display_frequency_of_keypad;		/* Mapped at index 0x2002, subindex 0x24 */
extern UNS16 Basic_Control_Parameters_Motor_Parameter_Enable;		/* Mapped at index 0x2002, subindex 0x29 */
extern UNS16 Basic_Control_Parameters_OEM_Password;		/* Mapped at index 0x2002, subindex 0x2A */
extern UNS16 Input_Terminal_Parameters_States_of_functions_not_allocated_among_FunIN_1_16_HEX;		/* Mapped at index 0x2003, subindex 0x01 */
extern UNS16 Input_Terminal_Parameters_States_of_functions_not_allocated_among_FunIN_17_32_HEX;		/* Mapped at index 0x2003, subindex 0x02 */
extern UNS16 Input_Terminal_Parameters_DI1_function_selection;		/* Mapped at index 0x2003, subindex 0x03 */
extern UNS16 Input_Terminal_Parameters_DI1_logic_selection;		/* Mapped at index 0x2003, subindex 0x04 */
extern UNS16 Input_Terminal_Parameters_DI2_function_selection;		/* Mapped at index 0x2003, subindex 0x05 */
extern UNS16 Input_Terminal_Parameters_DI2_logic_selection;		/* Mapped at index 0x2003, subindex 0x06 */
extern UNS16 Input_Terminal_Parameters_DI3_function_selection;		/* Mapped at index 0x2003, subindex 0x07 */
extern UNS16 Input_Terminal_Parameters_DI3_logic_selection;		/* Mapped at index 0x2003, subindex 0x08 */
extern UNS16 Input_Terminal_Parameters_DI4_function_selection;		/* Mapped at index 0x2003, subindex 0x09 */
extern UNS16 Input_Terminal_Parameters_DI4_logic_selection;		/* Mapped at index 0x2003, subindex 0x0A */
extern UNS16 Input_Terminal_Parameters_DI5_function_selection;		/* Mapped at index 0x2003, subindex 0x0B */
extern UNS16 Input_Terminal_Parameters_DI5_logic_selection;		/* Mapped at index 0x2003, subindex 0x0C */
extern UNS16 Input_Terminal_Parameters_DI6_function_selection;		/* Mapped at index 0x2003, subindex 0x0D */
extern UNS16 Input_Terminal_Parameters_DI6_logic_selection;		/* Mapped at index 0x2003, subindex 0x0E */
extern UNS16 Input_Terminal_Parameters_DI7_function_selection;		/* Mapped at index 0x2003, subindex 0x0F */
extern UNS16 Input_Terminal_Parameters_DI7_logic_selection;		/* Mapped at index 0x2003, subindex 0x10 */
extern UNS16 Input_Terminal_Parameters_DI8_function_selection;		/* Mapped at index 0x2003, subindex 0x11 */
extern UNS16 Input_Terminal_Parameters_DI8_logic_selection;		/* Mapped at index 0x2003, subindex 0x12 */
extern UNS16 Input_Terminal_Parameters_DI9_function_selection;		/* Mapped at index 0x2003, subindex 0x13 */
extern UNS16 Input_Terminal_Parameters_DI9_logic_selection;		/* Mapped at index 0x2003, subindex 0x14 */
extern UNS8 Input_Terminal_Parameters_Compatibility_Entry[48];		/* Mapped at index 0x2003, subindex 0x15 */
extern UNS16 Input_Terminal_Parameters_States_of_functions_not_allocatedamong_FunIN_33_48_HEX;		/* Mapped at index 0x2003, subindex 0x23 */
extern UNS16 Input_Terminal_Parameters_States_of_functions_not_allocatedamong_FunIN_49_64_HEX;		/* Mapped at index 0x2003, subindex 0x24 */
extern INTEGER16 Input_Terminal_Parameters_AI1_offset;		/* Mapped at index 0x2003, subindex 0x33 */
extern UNS16 Input_Terminal_Parameters_AI1_filter_time_constant;		/* Mapped at index 0x2003, subindex 0x34 */
extern UNS16 Input_Terminal_Parameters_AI1_Filter_Enable;		/* Mapped at index 0x2003, subindex 0x35 */
extern UNS16 Input_Terminal_Parameters_AI1_dead_zone;		/* Mapped at index 0x2003, subindex 0x36 */
extern INTEGER16 Input_Terminal_Parameters_AI1_zero_drift;		/* Mapped at index 0x2003, subindex 0x37 */
extern INTEGER16 Input_Terminal_Parameters_AI2_offset;		/* Mapped at index 0x2003, subindex 0x38 */
extern UNS16 Input_Terminal_Parameters_AI2_filter_time_constant;		/* Mapped at index 0x2003, subindex 0x39 */
extern UNS16 Input_Terminal_Parameters_AI2_Filter_Enable;		/* Mapped at index 0x2003, subindex 0x3A */
extern UNS16 Input_Terminal_Parameters_AI2_dead_zone;		/* Mapped at index 0x2003, subindex 0x3B */
extern INTEGER16 Input_Terminal_Parameters_AI2_zero_drift;		/* Mapped at index 0x2003, subindex 0x3C */
extern UNS16 Input_Terminal_Parameters_Speed_corresponding_to_10_V;		/* Mapped at index 0x2003, subindex 0x51 */
extern UNS16 Input_Terminal_Parameters_Torque_corresponding_to_10_V;		/* Mapped at index 0x2003, subindex 0x52 */
extern UNS16 Output_terminal_Parameters_DO1_function_selection;		/* Mapped at index 0x2004, subindex 0x01 */
extern UNS16 Output_terminal_Parameters_DO1_logic_selection;		/* Mapped at index 0x2004, subindex 0x02 */
extern UNS16 Output_terminal_Parameters_DO2_function_selection;		/* Mapped at index 0x2004, subindex 0x03 */
extern UNS16 Output_terminal_Parameters_DO2_logic_selection;		/* Mapped at index 0x2004, subindex 0x04 */
extern UNS16 Output_terminal_Parameters_DO3_function_selection;		/* Mapped at index 0x2004, subindex 0x05 */
extern UNS16 Output_terminal_Parameters_DO3_logic_selection;		/* Mapped at index 0x2004, subindex 0x06 */
extern UNS16 Output_terminal_Parameters_DO4_function_selection;		/* Mapped at index 0x2004, subindex 0x07 */
extern UNS16 Output_terminal_Parameters_DO4_logic_selection;		/* Mapped at index 0x2004, subindex 0x08 */
extern UNS16 Output_terminal_Parameters_DO5_function_selection;		/* Mapped at index 0x2004, subindex 0x09 */
extern UNS16 Output_terminal_Parameters_DO5_logic_selection;		/* Mapped at index 0x2004, subindex 0x0A */
extern UNS8 Output_terminal_Parameters_Compatibility_Entry[39];		/* Mapped at index 0x2004, subindex 0x0B */
extern UNS16 Output_terminal_Parameters_DO_source;		/* Mapped at index 0x2004, subindex 0x17 */
extern UNS16 Output_terminal_Parameters_AO1_signal_selection;		/* Mapped at index 0x2004, subindex 0x33 */
extern INTEGER16 Output_terminal_Parameters_AO1_offset_voltage;		/* Mapped at index 0x2004, subindex 0x34 */
extern INTEGER16 Output_terminal_Parameters_AO1_multiplying_factor;		/* Mapped at index 0x2004, subindex 0x35 */
extern UNS16 Output_terminal_Parameters_AO2_signal_selection;		/* Mapped at index 0x2004, subindex 0x36 */
extern INTEGER16 Output_terminal_Parameters_AO2_offset_voltage;		/* Mapped at index 0x2004, subindex 0x37 */
extern INTEGER16 Output_terminal_Parameters_AO2_multiplying_factor;		/* Mapped at index 0x2004, subindex 0x38 */
extern UNS16 Position_Control_Parameters_Position_reference_source;		/* Mapped at index 0x2005, subindex 0x01 */
extern UNS16 Position_Control_Parameters_Pulse_reference_input_terminal_selection;		/* Mapped at index 0x2005, subindex 0x02 */
extern UNS32 Position_Control_Parameters_Pulses_for_one_motor_revolution;		/* Mapped at index 0x2005, subindex 0x03 */
extern UNS8 Position_Control_Parameters_Compatibility_Entry[26];		/* Mapped at index 0x2005, subindex 0x04 */
extern UNS16 Position_Control_Parameters_First_order_lowpass_filter_time;		/* Mapped at index 0x2005, subindex 0x05 */
extern INTEGER16 Position_Control_Parameters_Step_size;		/* Mapped at index 0x2005, subindex 0x06 */
extern UNS16 Position_Control_Parameters_Filter_time_constant_of_of_average_value_of_position_reference;		/* Mapped at index 0x2005, subindex 0x07 */
extern UNS32 Position_Control_Parameters_Electronicgear_ratio_1_numerator;		/* Mapped at index 0x2005, subindex 0x08 */
extern UNS32 Position_Control_Parameters_Electronic_gear_ratio_1_denominator;		/* Mapped at index 0x2005, subindex 0x0A */
extern UNS32 Position_Control_Parameters_Electronicgear_ratio_2_numerator;		/* Mapped at index 0x2005, subindex 0x0C */
extern UNS32 Position_Control_Parameters_Electronic_gear_ratio_2_denominator;		/* Mapped at index 0x2005, subindex 0x0E */
extern UNS16 Position_Control_Parameters_Reference_pulse_form;		/* Mapped at index 0x2005, subindex 0x10 */
extern UNS16 Position_Control_Parameters_Clear_action;		/* Mapped at index 0x2005, subindex 0x11 */
extern UNS16 Position_Control_Parameters_Encoder_frequency_division_pulses;		/* Mapped at index 0x2005, subindex 0x12 */
extern UNS16 Position_Control_Parameters_Speed_feedforward_control_selection;		/* Mapped at index 0x2005, subindex 0x14 */
extern UNS16 Position_Control_Parameters_Output_condition_of_positioning_completed_signal_COIN;		/* Mapped at index 0x2005, subindex 0x15 */
extern UNS16 Position_Control_Parameters_Amplitude_for_positioning_completed;		/* Mapped at index 0x2005, subindex 0x16 */
extern UNS16 Position_Control_Parameters_Amplitude_of_positioning_almost_completed;		/* Mapped at index 0x2005, subindex 0x17 */
extern UNS16 Position_Control_Parameters_Control_of_home_return;		/* Mapped at index 0x2005, subindex 0x1F */
extern UNS16 Position_Control_Parameters_Mode_of_home_return;		/* Mapped at index 0x2005, subindex 0x20 */
extern UNS16 Position_Control_Parameters_HM_high_speed_searching;		/* Mapped at index 0x2005, subindex 0x21 */
extern UNS16 Position_Control_Parameters_HM_low_speed_searching;		/* Mapped at index 0x2005, subindex 0x22 */
extern UNS16 Position_Control_Parameters_HM_Acceleration_Deceleration_time;		/* Mapped at index 0x2005, subindex 0x23 */
extern UNS16 Position_Control_Parameters_Time_of_home_searching;		/* Mapped at index 0x2005, subindex 0x24 */
extern INTEGER32 Position_Control_Parameters_H0536;		/* Mapped at index 0x2005, subindex 0x25 */
extern UNS16 Position_Control_Parameters_Servo_pulse_output_source;		/* Mapped at index 0x2005, subindex 0x27 */
extern UNS16 Position_Control_Parameters_Electronic_gear_ratio_switchover_condition;		/* Mapped at index 0x2005, subindex 0x28 */
extern UNS16 Position_Control_Parameters_Output_polarity_of_Z_pulse;		/* Mapped at index 0x2005, subindex 0x2A */
extern UNS16 Position_Control_Parameters_Absolute_encode_multi_turns_offset;		/* Mapped at index 0x2005, subindex 0x2D */
extern INTEGER32 Position_Control_Parameters_Absolute_position_offset_of_absolute_encode_Low;		/* Mapped at index 0x2005, subindex 0x2F */
extern INTEGER32 Position_Control_Parameters_Absolute_position_offset_of_absolute_encode_High;		/* Mapped at index 0x2005, subindex 0x31 */
extern UNS16 Position_Control_Parameters_Mechanical_Gear_ratio_numerator_of_absolute_encode_mode_2;		/* Mapped at index 0x2005, subindex 0x33 */
extern UNS16 Position_Control_Parameters_Mechanical_Gear_ratio_denominator_of_absolute_encode_mode_2;		/* Mapped at index 0x2005, subindex 0x34 */
extern UNS32 Position_Control_Parameters_Max_value_of_mechanical_absolute_position_inc_of_absolute_encode_mode_2_Low;		/* Mapped at index 0x2005, subindex 0x35 */
extern UNS32 Position_Control_Parameters_Max_value_of_mechanical_absolute_position_inc_of_absolute_encode_mode_2_High;		/* Mapped at index 0x2005, subindex 0x37 */
extern UNS16 Position_Control_Parameters_Positon_reach_hold_time;		/* Mapped at index 0x2005, subindex 0x3D */
extern UNS32 Position_Control_Parameters_Position_window_unit_set;		/* Mapped at index 0x2005, subindex 0x3E */
extern UNS16 Speed_Control_Parameters_Main_speed_reference_A_source;		/* Mapped at index 0x2006, subindex 0x01 */
extern UNS16 Speed_Control_Parameters_Auxiliary_speed_reference_B_source;		/* Mapped at index 0x2006, subindex 0x02 */
extern UNS16 Speed_Control_Parameters_Speed_reference_selection;		/* Mapped at index 0x2006, subindex 0x03 */
extern INTEGER16 Speed_Control_Parameters_Keypad_setting_value_of_speed_reference;		/* Mapped at index 0x2006, subindex 0x04 */
extern UNS16 Speed_Control_Parameters_Jog_speed_setting_value;		/* Mapped at index 0x2006, subindex 0x05 */
extern UNS16 Speed_Control_Parameters_Acceleration_ramp_time_constant_of_speed_reference;		/* Mapped at index 0x2006, subindex 0x06 */
extern UNS16 Speed_Control_Parameters_Deceleration_ramp_time_constant_of_speed_reference;		/* Mapped at index 0x2006, subindex 0x07 */
extern UNS16 Speed_Control_Parameters_Maximum_speed_threshold;		/* Mapped at index 0x2006, subindex 0x08 */
extern UNS16 Speed_Control_Parameters_Forward_speed_threshold;		/* Mapped at index 0x2006, subindex 0x09 */
extern UNS16 Speed_Control_Parameters_Reverse_speed_threshold;		/* Mapped at index 0x2006, subindex 0x0A */
extern UNS8 Speed_Control_Parameters_Compatibility_Entry[4];		/* Mapped at index 0x2006, subindex 0x0B */
extern UNS16 Speed_Control_Parameters_Torque_feedforward_selection;		/* Mapped at index 0x2006, subindex 0x0C */
extern UNS16 Speed_Control_Parameters_Speed_limit_for_zero_clamp;		/* Mapped at index 0x2006, subindex 0x10 */
extern UNS16 Speed_Control_Parameters_Motor_speed_threshold;		/* Mapped at index 0x2006, subindex 0x11 */
extern UNS16 Speed_Control_Parameters_Threshold_of_speed_consistent_signal;		/* Mapped at index 0x2006, subindex 0x12 */
extern UNS16 Speed_Control_Parameters_Threshold_of_speed_reached_signal;		/* Mapped at index 0x2006, subindex 0x13 */
extern UNS16 Speed_Control_Parameters_Threshold_of_zero_speed_output_signal;		/* Mapped at index 0x2006, subindex 0x14 */
extern UNS16 Torque_Control_Parameters_Main_torque_reference_A_source;		/* Mapped at index 0x2007, subindex 0x01 */
extern UNS16 Torque_Control_Parameters_Auxiliary_torque_reference_B_source;		/* Mapped at index 0x2007, subindex 0x02 */
extern UNS16 Torque_Control_Parameters_Torque_reference_source;		/* Mapped at index 0x2007, subindex 0x03 */
extern INTEGER16 Torque_Control_Parameters_Keypad_setting_value_of_torque_reference;		/* Mapped at index 0x2007, subindex 0x04 */
extern UNS8 Torque_Control_Parameters_Compatibility_Entry[20];		/* Mapped at index 0x2007, subindex 0x05 */
extern UNS16 Torque_Control_Parameters_Torque_reference_filter_time;		/* Mapped at index 0x2007, subindex 0x06 */
extern UNS16 Torque_Control_Parameters_The_second_torque_reference_filter_time;		/* Mapped at index 0x2007, subindex 0x07 */
extern UNS16 Torque_Control_Parameters_Torque_limit_source;		/* Mapped at index 0x2007, subindex 0x08 */
extern UNS16 Torque_Control_Parameters_T_LMT_selection;		/* Mapped at index 0x2007, subindex 0x09 */
extern UNS16 Torque_Control_Parameters_Internal_forward_torque_limit;		/* Mapped at index 0x2007, subindex 0x0A */
extern UNS16 Torque_Control_Parameters_Internal_reverse_torque_limit;		/* Mapped at index 0x2007, subindex 0x0B */
extern UNS16 Torque_Control_Parameters_External_forward_torque_limit;		/* Mapped at index 0x2007, subindex 0x0C */
extern UNS16 Torque_Control_Parameters_External_reverse_torque_limit;		/* Mapped at index 0x2007, subindex 0x0D */
extern UNS16 Torque_Control_Parameters_Emergency_stop_torque;		/* Mapped at index 0x2007, subindex 0x10 */
extern UNS16 Torque_Control_Parameters_Speed_limit_source;		/* Mapped at index 0x2007, subindex 0x12 */
extern UNS16 Torque_Control_Parameters_V_LMT_selection;		/* Mapped at index 0x2007, subindex 0x13 */
extern UNS16 Torque_Control_Parameters_Forward_speed_limit_Speed_limit_1_in_torque_control;		/* Mapped at index 0x2007, subindex 0x14 */
extern UNS16 Torque_Control_Parameters_Reverse_speed_limit_Speed_limit_2_in_torque_control;		/* Mapped at index 0x2007, subindex 0x15 */
extern UNS16 Torque_Control_Parameters_Base_value_for_torque_reached;		/* Mapped at index 0x2007, subindex 0x16 */
extern UNS16 Torque_Control_Parameters_Threshold_of_torque_reached_valid;		/* Mapped at index 0x2007, subindex 0x17 */
extern UNS16 Torque_Control_Parameters_Threshold_of_torque_reached_invalid;		/* Mapped at index 0x2007, subindex 0x18 */
extern UNS16 Torque_Control_Parameters_Detection_time_of_speed_limit_exceeded;		/* Mapped at index 0x2007, subindex 0x29 */
extern UNS16 Gain_Parameters_Speed_loop_gain;		/* Mapped at index 0x2008, subindex 0x01 */
extern UNS16 Gain_Parameters_Speed_loop_integral_time_constant;		/* Mapped at index 0x2008, subindex 0x02 */
extern UNS16 Gain_Parameters_Position_loop_gain;		/* Mapped at index 0x2008, subindex 0x03 */
extern UNS16 Gain_Parameters_The_second_speed_loop_gain;		/* Mapped at index 0x2008, subindex 0x04 */
extern UNS16 Gain_Parameters_The_second_speed_loop_integral_time_constant;		/* Mapped at index 0x2008, subindex 0x05 */
extern UNS16 Gain_Parameters_The_second_position_loop_gain;		/* Mapped at index 0x2008, subindex 0x06 */
extern UNS8 Gain_Parameters_Compatibility_Entry[5];		/* Mapped at index 0x2008, subindex 0x07 */
extern UNS16 Gain_Parameters_Second_gain_mode_setting;		/* Mapped at index 0x2008, subindex 0x09 */
extern UNS16 Gain_Parameters_Gain_switchover_condition;		/* Mapped at index 0x2008, subindex 0x0A */
extern UNS16 Gain_Parameters_Gain_switchover_delay;		/* Mapped at index 0x2008, subindex 0x0B */
extern UNS16 Gain_Parameters_Gain_switchover_level;		/* Mapped at index 0x2008, subindex 0x0C */
extern UNS16 Gain_Parameters_Gain_switchover_hysteresis;		/* Mapped at index 0x2008, subindex 0x0D */
extern UNS16 Gain_Parameters_Position_gain_switchover_time;		/* Mapped at index 0x2008, subindex 0x0E */
extern UNS16 Gain_Parameters_Average_value_of_load_inertia_ratio;		/* Mapped at index 0x2008, subindex 0x10 */
extern UNS16 Gain_Parameters_Speed_feedforward_filter_time_constant;		/* Mapped at index 0x2008, subindex 0x13 */
extern UNS16 Gain_Parameters_Speed_feedforward_gain;		/* Mapped at index 0x2008, subindex 0x14 */
extern UNS16 Gain_Parameters_Torque_feedforward_filter_time_constant;		/* Mapped at index 0x2008, subindex 0x15 */
extern UNS16 Gain_Parameters_Torque_feedforward_gain;		/* Mapped at index 0x2008, subindex 0x16 */
extern UNS16 Gain_Parameters_Speed_feedback_filter;		/* Mapped at index 0x2008, subindex 0x17 */
extern UNS16 Gain_Parameters_Cutoff_frequency_of_speed_feedback_lowpass_filter;		/* Mapped at index 0x2008, subindex 0x18 */
extern UNS16 Gain_Parameters_Pseudo_differential_forward_feedback_control_coefficient;		/* Mapped at index 0x2008, subindex 0x19 */
extern UNS16 Auto_adjusting_Parameters_Auto_adjusting_mode;		/* Mapped at index 0x2009, subindex 0x01 */
extern UNS16 Auto_adjusting_Parameters_Rigidity_level_selection;		/* Mapped at index 0x2009, subindex 0x02 */
extern UNS16 Auto_adjusting_Parameters_Working_mode_of_self_adaptive_notch;		/* Mapped at index 0x2009, subindex 0x03 */
extern UNS16 Auto_adjusting_Parameters_Online_inertia_auto_tuning_mode;		/* Mapped at index 0x2009, subindex 0x04 */
extern UNS16 Auto_adjusting_Parameters_Low_frequency_vibration_mode_selection;		/* Mapped at index 0x2009, subindex 0x05 */
extern UNS16 Auto_adjusting_Parameters_Offline_inertia_auto_tuning_mode;		/* Mapped at index 0x2009, subindex 0x06 */
extern UNS16 Auto_adjusting_Parameters_Maximum_speed_for_inertia_autotuning;		/* Mapped at index 0x2009, subindex 0x07 */
extern UNS16 Auto_adjusting_Parameters_Acceleration_Deceleration_time_for_inertia_autotuning;		/* Mapped at index 0x2009, subindex 0x08 */
extern UNS16 Auto_adjusting_Parameters_Interval_after_an_inertia_autotuning;		/* Mapped at index 0x2009, subindex 0x09 */
extern UNS16 Auto_adjusting_Parameters_Motor_revolutions_for_an_inertia_auto_tuning;		/* Mapped at index 0x2009, subindex 0x0A */
extern UNS8 Auto_adjusting_Parameters_Compatibility_Entry[13];		/* Mapped at index 0x2009, subindex 0x0B */
extern UNS16 Auto_adjusting_Parameters_1st_notch_frequency;		/* Mapped at index 0x2009, subindex 0x0D */
extern UNS16 Auto_adjusting_Parameters_1st_notch_width_level;		/* Mapped at index 0x2009, subindex 0x0E */
extern UNS16 Auto_adjusting_Parameters_1st_notch_attenuation_level;		/* Mapped at index 0x2009, subindex 0x0F */
extern UNS16 Auto_adjusting_Parameters_2nd_notch_frequency;		/* Mapped at index 0x2009, subindex 0x10 */
extern UNS16 Auto_adjusting_Parameters_2nd_notch_width_level;		/* Mapped at index 0x2009, subindex 0x11 */
extern UNS16 Auto_adjusting_Parameters_2nd_notch_attenuation_level;		/* Mapped at index 0x2009, subindex 0x12 */
extern UNS16 Auto_adjusting_Parameters_3rd_notch_frequency;		/* Mapped at index 0x2009, subindex 0x13 */
extern UNS16 Auto_adjusting_Parameters_3rd_notch_width_level;		/* Mapped at index 0x2009, subindex 0x14 */
extern UNS16 Auto_adjusting_Parameters_3rd_notch_attenuation_level;		/* Mapped at index 0x2009, subindex 0x15 */
extern UNS16 Auto_adjusting_Parameters_4th_notch_frequency;		/* Mapped at index 0x2009, subindex 0x16 */
extern UNS16 Auto_adjusting_Parameters_4th_notch_width_level;		/* Mapped at index 0x2009, subindex 0x17 */
extern UNS16 Auto_adjusting_Parameters_4th_notch_attenuation_level;		/* Mapped at index 0x2009, subindex 0x18 */
extern UNS16 Auto_adjusting_Parameters_Obtained_resonance_frequency;		/* Mapped at index 0x2009, subindex 0x19 */
extern INTEGER16 Auto_adjusting_Parameters_Disturbance_torque_compensation_gain;		/* Mapped at index 0x2009, subindex 0x1F */
extern UNS16 Auto_adjusting_Parameters_Disturbance_observer_filter_time_constant;		/* Mapped at index 0x2009, subindex 0x20 */
extern UNS16 Auto_adjusting_Parameters_Low_frequency_vibration_frequency;		/* Mapped at index 0x2009, subindex 0x27 */
extern UNS16 Auto_adjusting_Parameters_Filter_of_low_frequency_vibration_frequency;		/* Mapped at index 0x2009, subindex 0x28 */
extern UNS16 Fault_and_Protection_Power_input_phase_loss_protection;		/* Mapped at index 0x200A, subindex 0x01 */
extern UNS16 Fault_and_Protection_Absolute_position_limit_set;		/* Mapped at index 0x200A, subindex 0x02 */
extern UNS8 Fault_and_Protection_Compatibility_Entry[12];		/* Mapped at index 0x200A, subindex 0x03 */
extern UNS16 Fault_and_Protection_Retentive_at_power_failure;		/* Mapped at index 0x200A, subindex 0x04 */
extern UNS16 Fault_and_Protection_Motor_overload_protection_gain;		/* Mapped at index 0x200A, subindex 0x05 */
extern UNS16 Fault_and_Protection_Overspeed_threshold;		/* Mapped at index 0x200A, subindex 0x09 */
extern UNS16 Fault_and_Protection_Maximum_position_pulse_frequency;		/* Mapped at index 0x200A, subindex 0x0A */
extern UNS32 Fault_and_Protection_Threshold_of_position_deviation_fault;		/* Mapped at index 0x200A, subindex 0x0B */
extern UNS16 Fault_and_Protection_Run_away_protection;		/* Mapped at index 0x200A, subindex 0x0D */
extern UNS16 Fault_and_Protection_Position_deviation_threshold_in_low_frequency_vibration;		/* Mapped at index 0x200A, subindex 0x11 */
extern UNS16 Fault_and_Protection_DI8_filter_time;		/* Mapped at index 0x200A, subindex 0x14 */
extern UNS16 Fault_and_Protection_DI9_filter_time;		/* Mapped at index 0x200A, subindex 0x15 */
extern UNS16 Fault_and_Protection_Sigma_delta_filter_time;		/* Mapped at index 0x200A, subindex 0x17 */
extern UNS16 Fault_and_Protection_Tz_signal_filter_time;		/* Mapped at index 0x200A, subindex 0x18 */
extern UNS16 Fault_and_Protection_Filter_time_of_low_speed_pulse_input_pin;		/* Mapped at index 0x200A, subindex 0x19 */
extern UNS16 Fault_and_Protection_Filter_time_of_speed_feedback_display;		/* Mapped at index 0x200A, subindex 0x1A */
extern UNS16 Fault_and_Protection_Motor_overload_shielding;		/* Mapped at index 0x200A, subindex 0x1B */
extern UNS16 Fault_and_Protection_Speed_DO_Filter_time_constant;		/* Mapped at index 0x200A, subindex 0x1C */
extern UNS16 Fault_and_Protection_Quadrature_encoder_filter_time;		/* Mapped at index 0x200A, subindex 0x1D */
extern UNS16 Fault_and_Protection_Line_encoder_filter_time;		/* Mapped at index 0x200A, subindex 0x1E */
extern UNS16 Fault_and_Protection_Filter_time_constant_of_high_speed_pulse_input_pin;		/* Mapped at index 0x200A, subindex 0x1F */
extern UNS16 Fault_and_Protection_Overheat_protection_time_duration_for_locked_rotor;		/* Mapped at index 0x200A, subindex 0x21 */
extern UNS16 Fault_and_Protection_Overheat_protection_for_locked_rotor;		/* Mapped at index 0x200A, subindex 0x22 */
extern INTEGER16 Display_Parameters_Actual_motor_rotational_speed_200B01;		/* Mapped at index 0x200B, subindex 0x01 */
extern INTEGER16 Display_Parameters_Speed_reference;		/* Mapped at index 0x200B, subindex 0x02 */
extern INTEGER16 Display_Parameters_Internal_torque_reference;		/* Mapped at index 0x200B, subindex 0x03 */
extern UNS16 Display_Parameters_Monitored_DI_states;		/* Mapped at index 0x200B, subindex 0x04 */
extern UNS8 Display_Parameters_Compatibility_Entry[35];		/* Mapped at index 0x200B, subindex 0x05 */
extern UNS16 Display_Parameters_Monitored_DO_states;		/* Mapped at index 0x200B, subindex 0x06 */
extern INTEGER32 Display_Parameters_Absolute_position_counter;		/* Mapped at index 0x200B, subindex 0x08 */
extern UNS16 Display_Parameters_Mechanical_angle;		/* Mapped at index 0x200B, subindex 0x0A */
extern UNS16 Display_Parameters_Electrical_angle;		/* Mapped at index 0x200B, subindex 0x0B */
extern INTEGER16 Display_Parameters_Speed_corresponding_to_input_position_reference;		/* Mapped at index 0x200B, subindex 0x0C */
extern UNS16 Display_Parameters_Average_load_rate;		/* Mapped at index 0x200B, subindex 0x0D */
extern INTEGER32 Display_Parameters_Input_reference_pulse_counter;		/* Mapped at index 0x200B, subindex 0x0E */
extern INTEGER32 Display_Parameters_Encoder_position_deviation_counter;		/* Mapped at index 0x200B, subindex 0x10 */
extern INTEGER32 Display_Parameters_Feedback_pulse_counter;		/* Mapped at index 0x200B, subindex 0x12 */
extern UNS32 Display_Parameters_Total_power_on_time;		/* Mapped at index 0x200B, subindex 0x14 */
extern INTEGER16 Display_Parameters_AI1_sampling_voltage;		/* Mapped at index 0x200B, subindex 0x16 */
extern INTEGER16 Display_Parameters_AI2_sampling_voltage;		/* Mapped at index 0x200B, subindex 0x17 */
extern UNS16 Display_Parameters_Phase_current_valid_value;		/* Mapped at index 0x200B, subindex 0x19 */
extern UNS16 Display_Parameters_Bus_voltage;		/* Mapped at index 0x200B, subindex 0x1B */
extern UNS16 Display_Parameters_Module_temperature;		/* Mapped at index 0x200B, subindex 0x1C */
extern UNS16 Display_Parameters_Displayed_fault_record;		/* Mapped at index 0x200B, subindex 0x22 */
extern UNS16 Display_Parameters_Fault_code;		/* Mapped at index 0x200B, subindex 0x23 */
extern UNS32 Display_Parameters_Time_stamp_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x24 */
extern INTEGER16 Display_Parameters_Current_rotational_speed_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x26 */
extern INTEGER16 Display_Parameters_Current_U_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x27 */
extern INTEGER16 Display_Parameters_Current_V_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x28 */
extern UNS16 Display_Parameters_Bus_voltage_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x29 */
extern UNS16 Display_Parameters_Input_terminal_state_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x2A */
extern UNS16 Display_Parameters_Output_terminal_state_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x2B */
extern UNS16 Display_Parameters_Group_of_unusual_function_code;		/* Mapped at index 0x200B, subindex 0x2C */
extern UNS16 Display_Parameters_Offset_of_unusual_function_code;		/* Mapped at index 0x200B, subindex 0x2D */
extern UNS16 Display_Parameters_Inner_error_code;		/* Mapped at index 0x200B, subindex 0x2E */
extern UNS16 Display_Parameters_Fault_message_of_absolute_encode_from_Fpga_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x2F */
extern UNS16 Display_Parameters_System_state_from_Fpga_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x30 */
extern UNS16 Display_Parameters_System_fault_message_from_Fpga_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x31 */
extern UNS16 Display_Parameters_Encode_state_1_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x32 */
extern UNS16 Display_Parameters_Inner_error_code_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x34 */
extern UNS16 Display_Parameters_Fpga_overtime_state_upon_displayed_fault;		/* Mapped at index 0x200B, subindex 0x35 */
extern INTEGER32 Display_Parameters_Reference_position_deviation;		/* Mapped at index 0x200B, subindex 0x36 */
extern INTEGER32 Display_Parameters_Actual_motor_rotational_speed_200B38;		/* Mapped at index 0x200B, subindex 0x38 */
extern UNS16 Display_Parameters_Control_bus_voltage;		/* Mapped at index 0x200B, subindex 0x3A */
extern INTEGER32 Display_Parameters_Mechanical_absolute_position_inc_Low;		/* Mapped at index 0x200B, subindex 0x3B */
extern INTEGER32 Display_Parameters_Mechanical_absolute_position_inc_High;		/* Mapped at index 0x200B, subindex 0x3D */
extern INTEGER32 Display_Parameters_Real_Time_Input_reference_pulse_counter;		/* Mapped at index 0x200B, subindex 0x41 */
extern UNS16 Display_Parameters_Fpga_over_time_state;		/* Mapped at index 0x200B, subindex 0x45 */
extern UNS16 Display_Parameters_Number_of_turns_of_absolute_encode;		/* Mapped at index 0x200B, subindex 0x47 */
extern INTEGER32 Display_Parameters_Single_feedback_postion_of_absolute_encode;		/* Mapped at index 0x200B, subindex 0x48 */
extern INTEGER32 Display_Parameters_feedback_postion_of_absolute_encode_Low;		/* Mapped at index 0x200B, subindex 0x4E */
extern INTEGER32 Display_Parameters_feedback_postion_of_absolute_encode_High;		/* Mapped at index 0x200B, subindex 0x50 */
extern UNS32 Display_Parameters_feedback_postion_inc_of_rotating_load_Low;		/* Mapped at index 0x200B, subindex 0x52 */
extern UNS32 Display_Parameters_feedback_postion_inc_of_rotating_load_High;		/* Mapped at index 0x200B, subindex 0x54 */
extern UNS32 Display_Parameters_Single_feedback_postion_of_rotating_load;		/* Mapped at index 0x200B, subindex 0x56 */
extern UNS16 Communication_Parameters_Servo_shaft_address;		/* Mapped at index 0x200C, subindex 0x01 */
extern UNS8 Communication_Parameters_Compatibility_Entry[20];		/* Mapped at index 0x200C, subindex 0x02 */
extern UNS16 Communication_Parameters_Serial_port_baud_rate;		/* Mapped at index 0x200C, subindex 0x03 */
extern UNS16 Communication_Parameters_Modbus_data_format;		/* Mapped at index 0x200C, subindex 0x04 */
extern UNS16 Communication_Parameters_CAN_communication_rate;		/* Mapped at index 0x200C, subindex 0x09 */
extern UNS16 Communication_Parameters_Communication_virtual_DI;		/* Mapped at index 0x200C, subindex 0x0A */
extern UNS16 Communication_Parameters_Default_virtual_level_of_VDI_at_power_on;		/* Mapped at index 0x200C, subindex 0x0B */
extern UNS16 Communication_Parameters_Communication_virtual_DO;		/* Mapped at index 0x200C, subindex 0x0C */
extern UNS16 Communication_Parameters_Default_virtual_level_of_VDO_allocated_with_function_0;		/* Mapped at index 0x200C, subindex 0x0D */
extern UNS16 Communication_Parameters_Update_function_code_values_written_via_communication_to_EEPROM;		/* Mapped at index 0x200C, subindex 0x0E */
extern UNS16 Communication_Parameters_Modbus_Error_code;		/* Mapped at index 0x200C, subindex 0x0F */
extern UNS16 Communication_Parameters_Modbus_send_delay_time;		/* Mapped at index 0x200C, subindex 0x1A */
extern UNS16 Communication_Parameters_Modbus_32_bit_function_code_transmission_sequence;		/* Mapped at index 0x200C, subindex 0x1B */
extern UNS16 Communication_Parameters_CAN_Receive_Frame_Counter_Per_Second;		/* Mapped at index 0x200C, subindex 0x21 */
extern UNS16 Communication_Parameters_CAN_Max_Receive_Frame_Error_Counter_Per_Second;		/* Mapped at index 0x200C, subindex 0x22 */
extern UNS16 Communication_Parameters_CAN_Max_Transmit_Frame_Error_Counter_Per_Second;		/* Mapped at index 0x200C, subindex 0x23 */
extern UNS16 Communication_Parameters_CAN_Bus_Off_Counter_Per_Second;		/* Mapped at index 0x200C, subindex 0x24 */
extern UNS16 Auxiliary_Function_Parameters_Software_reset;		/* Mapped at index 0x200D, subindex 0x01 */
extern UNS16 Auxiliary_Function_Parameters_Fault_reset;		/* Mapped at index 0x200D, subindex 0x02 */
extern UNS16 Auxiliary_Function_Parameters_Load_inertia_autotuning;		/* Mapped at index 0x200D, subindex 0x03 */
extern UNS8 Auxiliary_Function_Parameters_Compatibility_Entry[11];		/* Mapped at index 0x200D, subindex 0x04 */
extern UNS16 Auxiliary_Function_Parameters_Emergency_stop;		/* Mapped at index 0x200D, subindex 0x06 */
extern UNS16 Auxiliary_Function_Parameters_Analog_automatic_adjustment;		/* Mapped at index 0x200D, subindex 0x0B */
extern UNS16 Auxiliary_Function_Parameters_Jog_function;		/* Mapped at index 0x200D, subindex 0x0C */
extern UNS16 Auxiliary_Function_Parameters_Forced_input_and_output_mode_of_DI_DO;		/* Mapped at index 0x200D, subindex 0x12 */
extern UNS16 Auxiliary_Function_Parameters_Forced_input_setting_of_DI;		/* Mapped at index 0x200D, subindex 0x13 */
extern UNS16 Auxiliary_Function_Parameters_Forced_output_setting_of_DO;		/* Mapped at index 0x200D, subindex 0x14 */
extern UNS16 Auxiliary_Function_Parameters_Absolute_encoder_alarm_reset;		/* Mapped at index 0x200D, subindex 0x15 */
extern UNS16 Full_Closed_loop_Parameters_Encoder_feedback_mode;		/* Mapped at index 0x200F, subindex 0x01 */
extern UNS16 Full_Closed_loop_Parameters_Running_mode_of_external_encoder;		/* Mapped at index 0x200F, subindex 0x02 */
extern UNS8 Full_Closed_loop_Parameters_Compatibility_Entry[12];		/* Mapped at index 0x200F, subindex 0x03 */
extern UNS32 Full_Closed_loop_Parameters_External_encoder_pulses_per_motor_revolution;		/* Mapped at index 0x200F, subindex 0x05 */
extern UNS32 Full_Closed_loop_Parameters_Hybrid_deviation_excess_setting;		/* Mapped at index 0x200F, subindex 0x09 */
extern UNS16 Full_Closed_loop_Parameters_Hybrid_deviation_clear_setting;		/* Mapped at index 0x200F, subindex 0x0B */
extern UNS16 Full_Closed_loop_Parameters_First_order_lowpass_filter_time_of_external_internal_deviation;		/* Mapped at index 0x200F, subindex 0x0E */
extern UNS32 Full_Closed_loop_Parameters_Hybrid_deviation_counter;		/* Mapped at index 0x200F, subindex 0x11 */
extern UNS32 Full_Closed_loop_Parameters_Pulse_feedback_display_of_internal_encoder;		/* Mapped at index 0x200F, subindex 0x13 */
extern UNS32 Full_Closed_loop_Parameters_Pulse_feedback_display_of_external_encoder;		/* Mapped at index 0x200F, subindex 0x15 */
extern UNS16 Multi_Position_Function_Parameters_Multi_position_running_mode;		/* Mapped at index 0x2011, subindex 0x01 */
extern UNS16 Multi_Position_Function_Parameters_Number_of_position_reference_profile;		/* Mapped at index 0x2011, subindex 0x02 */
extern UNS16 Multi_Position_Function_Parameters_Margin_processing_method;		/* Mapped at index 0x2011, subindex 0x03 */
extern UNS16 Multi_Position_Function_Parameters_Time_unit;		/* Mapped at index 0x2011, subindex 0x04 */
extern UNS16 Multi_Position_Function_Parameters_Displacement_reference_type;		/* Mapped at index 0x2011, subindex 0x05 */
extern UNS16 Multi_Position_Function_Parameters_Start_position_of_sequential_running;		/* Mapped at index 0x2011, subindex 0x06 */
extern UNS8 Multi_Position_Function_Parameters_Compatibility_Entry[22];		/* Mapped at index 0x2011, subindex 0x07 */
extern INTEGER32 Multi_Position_Function_Parameters_1st_displacement;		/* Mapped at index 0x2011, subindex 0x0D */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_1st_displacement;		/* Mapped at index 0x2011, subindex 0x0F */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_1st_displacement;		/* Mapped at index 0x2011, subindex 0x10 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_1st_displacement;		/* Mapped at index 0x2011, subindex 0x11 */
extern INTEGER32 Multi_Position_Function_Parameters_2nd_displacement;		/* Mapped at index 0x2011, subindex 0x12 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_2nd_displacement;		/* Mapped at index 0x2011, subindex 0x14 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_2nd_displacement;		/* Mapped at index 0x2011, subindex 0x15 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_2nd_displacement;		/* Mapped at index 0x2011, subindex 0x16 */
extern INTEGER32 Multi_Position_Function_Parameters_3rd_displacement;		/* Mapped at index 0x2011, subindex 0x17 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_3rd_displacement;		/* Mapped at index 0x2011, subindex 0x19 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_3rd_displacement;		/* Mapped at index 0x2011, subindex 0x1A */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_3rddisplacement;		/* Mapped at index 0x2011, subindex 0x1B */
extern INTEGER32 Multi_Position_Function_Parameters_4th_displacement;		/* Mapped at index 0x2011, subindex 0x1C */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_4th_displacement;		/* Mapped at index 0x2011, subindex 0x1E */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_4th_displacement;		/* Mapped at index 0x2011, subindex 0x1F */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_4th_displacement;		/* Mapped at index 0x2011, subindex 0x20 */
extern INTEGER32 Multi_Position_Function_Parameters_5th_displacement;		/* Mapped at index 0x2011, subindex 0x21 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_5th_displacement;		/* Mapped at index 0x2011, subindex 0x23 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_5th_displacement;		/* Mapped at index 0x2011, subindex 0x24 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_5th_displacement;		/* Mapped at index 0x2011, subindex 0x25 */
extern INTEGER32 Multi_Position_Function_Parameters_6th_displacement;		/* Mapped at index 0x2011, subindex 0x26 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_6th_displacement;		/* Mapped at index 0x2011, subindex 0x28 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_6th_displacement;		/* Mapped at index 0x2011, subindex 0x29 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_6th_displacement;		/* Mapped at index 0x2011, subindex 0x2A */
extern INTEGER32 Multi_Position_Function_Parameters_7th_displacement;		/* Mapped at index 0x2011, subindex 0x2B */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_7th_displacement;		/* Mapped at index 0x2011, subindex 0x2D */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_7th_displacement;		/* Mapped at index 0x2011, subindex 0x2E */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_7th_displacement;		/* Mapped at index 0x2011, subindex 0x2F */
extern INTEGER32 Multi_Position_Function_Parameters_8th_displacement;		/* Mapped at index 0x2011, subindex 0x30 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_8th_displacement;		/* Mapped at index 0x2011, subindex 0x32 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_8th_displacement;		/* Mapped at index 0x2011, subindex 0x33 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_8th_displacement;		/* Mapped at index 0x2011, subindex 0x34 */
extern INTEGER32 Multi_Position_Function_Parameters_9th_displacement;		/* Mapped at index 0x2011, subindex 0x35 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_9th_displacement;		/* Mapped at index 0x2011, subindex 0x37 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_9th_displacement;		/* Mapped at index 0x2011, subindex 0x38 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_9th_displacement;		/* Mapped at index 0x2011, subindex 0x39 */
extern INTEGER32 Multi_Position_Function_Parameters_10th_displacement;		/* Mapped at index 0x2011, subindex 0x3A */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_10th_displacement;		/* Mapped at index 0x2011, subindex 0x3C */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_10th_displacement;		/* Mapped at index 0x2011, subindex 0x3D */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_10th_displacement;		/* Mapped at index 0x2011, subindex 0x3E */
extern INTEGER32 Multi_Position_Function_Parameters_11th_displacement;		/* Mapped at index 0x2011, subindex 0x3F */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_11th_displacement;		/* Mapped at index 0x2011, subindex 0x41 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_11th_displacement;		/* Mapped at index 0x2011, subindex 0x42 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_11th_displacement;		/* Mapped at index 0x2011, subindex 0x43 */
extern INTEGER32 Multi_Position_Function_Parameters_12th_displacement;		/* Mapped at index 0x2011, subindex 0x44 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_12th_displacement;		/* Mapped at index 0x2011, subindex 0x46 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_12th_displacement;		/* Mapped at index 0x2011, subindex 0x47 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_12th_displacement;		/* Mapped at index 0x2011, subindex 0x48 */
extern INTEGER32 Multi_Position_Function_Parameters_13th_displacement;		/* Mapped at index 0x2011, subindex 0x49 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_13th_displacement;		/* Mapped at index 0x2011, subindex 0x4B */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_13th_displacement;		/* Mapped at index 0x2011, subindex 0x4C */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_13th_displacement;		/* Mapped at index 0x2011, subindex 0x4D */
extern INTEGER32 Multi_Position_Function_Parameters_14th_displacement;		/* Mapped at index 0x2011, subindex 0x4E */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_14th_displacement;		/* Mapped at index 0x2011, subindex 0x50 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_14th_displacement;		/* Mapped at index 0x2011, subindex 0x51 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_14th_displacement;		/* Mapped at index 0x2011, subindex 0x52 */
extern INTEGER32 Multi_Position_Function_Parameters_15th_displacement;		/* Mapped at index 0x2011, subindex 0x53 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_15th_displacement;		/* Mapped at index 0x2011, subindex 0x55 */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_15th_displacement;		/* Mapped at index 0x2011, subindex 0x56 */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_15th_displacement;		/* Mapped at index 0x2011, subindex 0x57 */
extern INTEGER32 Multi_Position_Function_Parameters_16th_displacement;		/* Mapped at index 0x2011, subindex 0x58 */
extern UNS16 Multi_Position_Function_Parameters_Maximum_running_speed_of_16th_displacement;		/* Mapped at index 0x2011, subindex 0x5A */
extern UNS16 Multi_Position_Function_Parameters_Acceleration_Deceleration_time_of_16th_displacement;		/* Mapped at index 0x2011, subindex 0x5B */
extern UNS16 Multi_Position_Function_Parameters_Waiting_time_after_16th_displacement;		/* Mapped at index 0x2011, subindex 0x5C */
extern UNS16 VDI_VDO_Parameters_VDI1_function_selection;		/* Mapped at index 0x2017, subindex 0x01 */
extern UNS16 VDI_VDO_Parameters_VDI1_logic_selection;		/* Mapped at index 0x2017, subindex 0x02 */
extern UNS16 VDI_VDO_Parameters_VDI2_function_selection;		/* Mapped at index 0x2017, subindex 0x03 */
extern UNS16 VDI_VDO_Parameters_VDI2_logic_selection;		/* Mapped at index 0x2017, subindex 0x04 */
extern UNS16 VDI_VDO_Parameters_VDI3_function_selection;		/* Mapped at index 0x2017, subindex 0x05 */
extern UNS16 VDI_VDO_Parameters_VDI3_logic_selection;		/* Mapped at index 0x2017, subindex 0x06 */
extern UNS16 VDI_VDO_Parameters_VDI4_function_selection;		/* Mapped at index 0x2017, subindex 0x07 */
extern UNS16 VDI_VDO_Parameters_VDI4_logic_selection;		/* Mapped at index 0x2017, subindex 0x08 */
extern UNS16 VDI_VDO_Parameters_VDI5_function_selection;		/* Mapped at index 0x2017, subindex 0x09 */
extern UNS16 VDI_VDO_Parameters_VDI5_logic_selection;		/* Mapped at index 0x2017, subindex 0x0A */
extern UNS16 VDI_VDO_Parameters_VDI6_function_selection;		/* Mapped at index 0x2017, subindex 0x0B */
extern UNS16 VDI_VDO_Parameters_VDI6_logic_selection;		/* Mapped at index 0x2017, subindex 0x0C */
extern UNS16 VDI_VDO_Parameters_VDI7_function_selection;		/* Mapped at index 0x2017, subindex 0x0D */
extern UNS16 VDI_VDO_Parameters_VDI7_logic_selection;		/* Mapped at index 0x2017, subindex 0x0E */
extern UNS16 VDI_VDO_Parameters_VDI8_function_selection;		/* Mapped at index 0x2017, subindex 0x0F */
extern UNS16 VDI_VDO_Parameters_VD8_logic_selection;		/* Mapped at index 0x2017, subindex 0x10 */
extern UNS16 VDI_VDO_Parameters_VDI9_function_selection;		/* Mapped at index 0x2017, subindex 0x11 */
extern UNS16 VDI_VDO_Parameters_VDI9_logic_selection;		/* Mapped at index 0x2017, subindex 0x12 */
extern UNS16 VDI_VDO_Parameters_VDI10_function_selection;		/* Mapped at index 0x2017, subindex 0x13 */
extern UNS16 VDI_VDO_Parameters_VDI10_logic_selection;		/* Mapped at index 0x2017, subindex 0x14 */
extern UNS16 VDI_VDO_Parameters_VDI11_function_selection;		/* Mapped at index 0x2017, subindex 0x15 */
extern UNS16 VDI_VDO_Parameters_VDI11_logic_selection;		/* Mapped at index 0x2017, subindex 0x16 */
extern UNS16 VDI_VDO_Parameters_VDI12_function_selection;		/* Mapped at index 0x2017, subindex 0x17 */
extern UNS16 VDI_VDO_Parameters_VDI12_logic_selection;		/* Mapped at index 0x2017, subindex 0x18 */
extern UNS16 VDI_VDO_Parameters_VDI13_function_selection;		/* Mapped at index 0x2017, subindex 0x19 */
extern UNS16 VDI_VDO_Parameters_VDI13_logic_selection;		/* Mapped at index 0x2017, subindex 0x1A */
extern UNS16 VDI_VDO_Parameters_VDI14_function_selection;		/* Mapped at index 0x2017, subindex 0x1B */
extern UNS16 VDI_VDO_Parameters_VDI14_logic_selection;		/* Mapped at index 0x2017, subindex 0x1C */
extern UNS16 VDI_VDO_Parameters_VDI15_function_selection;		/* Mapped at index 0x2017, subindex 0x1D */
extern UNS16 VDI_VDO_Parameters_VDI15_logic_selection;		/* Mapped at index 0x2017, subindex 0x1E */
extern UNS16 VDI_VDO_Parameters_VDI16_function_selection;		/* Mapped at index 0x2017, subindex 0x1F */
extern UNS16 VDI_VDO_Parameters_VDI16_logic_selection;		/* Mapped at index 0x2017, subindex 0x20 */
extern UNS16 VDI_VDO_Parameters_VDO_virtual_level;		/* Mapped at index 0x2017, subindex 0x21 */
extern UNS16 VDI_VDO_Parameters_VDO1_function_selection;		/* Mapped at index 0x2017, subindex 0x22 */
extern UNS16 VDI_VDO_Parameters_VDO1_logic_selection;		/* Mapped at index 0x2017, subindex 0x23 */
extern UNS16 VDI_VDO_Parameters_VDO2_function_selection;		/* Mapped at index 0x2017, subindex 0x24 */
extern UNS16 VDI_VDO_Parameters_VDO2_logic_selection;		/* Mapped at index 0x2017, subindex 0x25 */
extern UNS16 VDI_VDO_Parameters_VDO3_function_selection;		/* Mapped at index 0x2017, subindex 0x26 */
extern UNS16 VDI_VDO_Parameters_VDO3_logic_selection;		/* Mapped at index 0x2017, subindex 0x27 */
extern UNS16 VDI_VDO_Parameters_VDO4_function_selection;		/* Mapped at index 0x2017, subindex 0x28 */
extern UNS16 VDI_VDO_Parameters_VDO4_logic_selection;		/* Mapped at index 0x2017, subindex 0x29 */
extern UNS16 VDI_VDO_Parameters_VDO5_function_selection;		/* Mapped at index 0x2017, subindex 0x2A */
extern UNS16 VDI_VDO_Parameters_VDO5_logic_selection;		/* Mapped at index 0x2017, subindex 0x2B */
extern UNS16 VDI_VDO_Parameters_VDO6_function_selection;		/* Mapped at index 0x2017, subindex 0x2C */
extern UNS16 VDI_VDO_Parameters_VDO6_logic_selection;		/* Mapped at index 0x2017, subindex 0x2D */
extern UNS16 VDI_VDO_Parameters_VDO7_function_selection;		/* Mapped at index 0x2017, subindex 0x2E */
extern UNS16 VDI_VDO_Parameters_VDO7_logic_selection;		/* Mapped at index 0x2017, subindex 0x2F */
extern UNS16 VDI_VDO_Parameters_VDO8_function_selection;		/* Mapped at index 0x2017, subindex 0x30 */
extern UNS16 VDI_VDO_Parameters_VDO8_logic_selection;		/* Mapped at index 0x2017, subindex 0x31 */
extern UNS16 VDI_VDO_Parameters_VDO9_function_selection;		/* Mapped at index 0x2017, subindex 0x32 */
extern UNS16 VDI_VDO_Parameters_VDO9_logic_selection;		/* Mapped at index 0x2017, subindex 0x33 */
extern UNS16 VDI_VDO_Parameters_VDO10_function_selection;		/* Mapped at index 0x2017, subindex 0x34 */
extern UNS16 VDI_VDO_Parameters_VDO10_logic_selection;		/* Mapped at index 0x2017, subindex 0x35 */
extern UNS16 VDI_VDO_Parameters_VDO11_function_selection;		/* Mapped at index 0x2017, subindex 0x36 */
extern UNS16 VDI_VDO_Parameters_VDO11_logic_selection;		/* Mapped at index 0x2017, subindex 0x37 */
extern UNS16 VDI_VDO_Parameters_VDO12_function_selection;		/* Mapped at index 0x2017, subindex 0x38 */
extern UNS16 VDI_VDO_Parameters_VDO12_logic_selection;		/* Mapped at index 0x2017, subindex 0x39 */
extern UNS16 VDI_VDO_Parameters_VDO13_function_selection;		/* Mapped at index 0x2017, subindex 0x3A */
extern UNS16 VDI_VDO_Parameters_VDO13_logic_selection;		/* Mapped at index 0x2017, subindex 0x3B */
extern UNS16 VDI_VDO_Parameters_VDO14_function_selection;		/* Mapped at index 0x2017, subindex 0x3C */
extern UNS16 VDI_VDO_Parameters_VDO14_logic_selection;		/* Mapped at index 0x2017, subindex 0x3D */
extern UNS16 VDI_VDO_Parameters_VDO15_function_selection;		/* Mapped at index 0x2017, subindex 0x3E */
extern UNS16 VDI_VDO_Parameters_VDO15_logic_selection;		/* Mapped at index 0x2017, subindex 0x3F */
extern UNS16 VDI_VDO_Parameters_VDO16_function_selection;		/* Mapped at index 0x2017, subindex 0x40 */
extern UNS16 VDI_VDO_Parameters_VDO16_logic_selection;		/* Mapped at index 0x2017, subindex 0x41 */
extern UNS16 Servo_Related_Variables_Read_via_Communication_Servo_state_read_via_communication;		/* Mapped at index 0x2030, subindex 0x01 */
extern UNS16 Servo_Related_Variables_Read_via_Communication_DO_function_state_1_read_via_communication;		/* Mapped at index 0x2030, subindex 0x02 */
extern UNS16 Servo_Related_Variables_Read_via_Communication_DO_function_state_2_read_via_communication;		/* Mapped at index 0x2030, subindex 0x03 */
extern UNS16 Servo_Related_Variables_Read_via_Communication_Input_reference_pulse_sampling_read_via_communication;		/* Mapped at index 0x2030, subindex 0x04 */
extern UNS16 Servo_Related_Variables_Set_via_Communication_VDI_virtuallevel_set_via_communication;		/* Mapped at index 0x2031, subindex 0x01 */
extern UNS8 Servo_Related_Variables_Set_via_Communication_Compatibility_Entry[8];		/* Mapped at index 0x2031, subindex 0x02 */
extern UNS16 Servo_Related_Variables_Set_via_Communication_DO_state_set_via_communication;		/* Mapped at index 0x2031, subindex 0x05 */
extern INTEGER32 Servo_Related_Variables_Set_via_Communication_Speed_reference_set_via_communication;		/* Mapped at index 0x2031, subindex 0x0A */
extern INTEGER32 Servo_Related_Variables_Set_via_Communication_Torque_reference_set_via_communication;		/* Mapped at index 0x2031, subindex 0x0C */
extern UNS32 Inovance_drive_fault_code;		/* Mapped at index 0x203F, subindex 0x00*/
extern UNS16 Error_code;		/* Mapped at index 0x603F, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER16 Quick_stop_option_code;		/* Mapped at index 0x605A, subindex 0x00*/
extern INTEGER16 Halt_option_code;		/* Mapped at index 0x605D, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER8 Modes_of_operation_display;		/* Mapped at index 0x6061, subindex 0x00*/
extern INTEGER32 Position_demannd_value;		/* Mapped at index 0x6062, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6063, subindex 0x00*/
extern INTEGER32 Position_actual_value_user;		/* Mapped at index 0x6064, subindex 0x00*/
extern UNS32 Maximal_following_error;		/* Mapped at index 0x6065, subindex 0x00*/
extern UNS32 Following_error_timeout;		/* Mapped at index 0x6066, subindex 0x00*/
extern UNS32 Position_window;		/* Mapped at index 0x6067, subindex 0x00*/
extern UNS16 Position_window_time;		/* Mapped at index 0x6068, subindex 0x00*/
extern INTEGER32 Velocity_demand_value;		/* Mapped at index 0x606B, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern UNS16 Velocity_window;		/* Mapped at index 0x606D, subindex 0x00*/
extern UNS16 Velocity_window_time;		/* Mapped at index 0x606E, subindex 0x00*/
extern UNS16 Velocity_threshold;		/* Mapped at index 0x606F, subindex 0x00*/
extern UNS16 Velocity_threshold_time;		/* Mapped at index 0x6070, subindex 0x00*/
extern INTEGER16 Target_Torque;		/* Mapped at index 0x6071, subindex 0x00*/
extern UNS16 Max_Torque;		/* Mapped at index 0x6072, subindex 0x00*/
extern INTEGER16 ToqDemandValue;		/* Mapped at index 0x6074, subindex 0x00*/
extern INTEGER16 Torque_Actual_Value;		/* Mapped at index 0x6077, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern INTEGER32 Home_offset;		/* Mapped at index 0x607C, subindex 0x00*/
extern INTEGER32 Software_position_limit_Minimal_position_limit;		/* Mapped at index 0x607D, subindex 0x01 */
extern INTEGER32 Software_position_limit_Maximal_position_limit;		/* Mapped at index 0x607D, subindex 0x02 */
extern UNS8 Polarity;		/* Mapped at index 0x607E, subindex 0x00*/
extern UNS32 Maximal_profile_velocity;		/* Mapped at index 0x607F, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern UNS32 Profile_acceleration;		/* Mapped at index 0x6083, subindex 0x00*/
extern UNS32 Profile_deceleration;		/* Mapped at index 0x6084, subindex 0x00*/
extern UNS32 Quick_stop_deceleration;		/* Mapped at index 0x6085, subindex 0x00*/
extern INTEGER16 Motion_profile_type;		/* Mapped at index 0x6086, subindex 0x00*/
extern UNS32 Torque_Slope;		/* Mapped at index 0x6087, subindex 0x00*/
extern UNS32 GearRatio_MotorRev;		/* Mapped at index 0x6091, subindex 0x01 */
extern UNS32 GearRatio_ShaftRev;		/* Mapped at index 0x6091, subindex 0x02 */
extern INTEGER8 Homing_method;		/* Mapped at index 0x6098, subindex 0x00*/
extern UNS32 Homing_speeds_Speed_for_switch_search;		/* Mapped at index 0x6099, subindex 0x01 */
extern UNS32 Homing_speeds_Speed_for_zero_search;		/* Mapped at index 0x6099, subindex 0x02 */
extern UNS32 Homing_acceleration;		/* Mapped at index 0x609A, subindex 0x00*/
extern INTEGER32 Interpolated_data_record_the_first_parameter_of_ip_function;		/* Mapped at index 0x60C1, subindex 0x01 */
extern UNS8 Interpolation_time_period_ip_time_units;		/* Mapped at index 0x60C2, subindex 0x01 */
extern INTEGER8 Interpolation_time_period_ip_time_index;		/* Mapped at index 0x60C2, subindex 0x02 */
extern UNS32 Max_acceleration;		/* Mapped at index 0x60C5, subindex 0x00*/
extern UNS32 Max_deceleration;		/* Mapped at index 0x60C6, subindex 0x00*/
extern UNS16 MAX_positive_torque_limit;		/* Mapped at index 0x60E0, subindex 0x00*/
extern UNS16 MAX_negative_torque_limit;		/* Mapped at index 0x60E1, subindex 0x00*/
extern UNS8 Actual_pos_calculate_method;		/* Mapped at index 0x60E6, subindex 0x00*/
extern INTEGER32 Following_error_actual_value;		/* Mapped at index 0x60F4, subindex 0x00*/
extern INTEGER32 Position_demand_value;		/* Mapped at index 0x60FC, subindex 0x00*/
extern UNS32 Digital_inputs;		/* Mapped at index 0x60FD, subindex 0x00*/
extern UNS32 Digital_outputs_Physical_outputs;		/* Mapped at index 0x60FE, subindex 0x01 */
extern UNS32 Digital_outputs_empty;		/* Mapped at index 0x60FE, subindex 0x02 */
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/
extern UNS32 Supported_drive_modes;		/* Mapped at index 0x6502, subindex 0x00*/

#endif // CANFESTIVAL_MASTER_H
